### ISSUE TITLE
Various improvements to this project

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/umd-lhcb.github.io#9]
I've made these improvements:

1. Added Svende's picture. Internally, every list entry in the `people.yml` can optionally has a `photos` key, which must be a list, and each list element should contain `file` and `caption` key.

    More over, if the `photos` contains only 1 element, then the photo will be full-width, otherwise they will be half-width

2. Smarter line break: In `people.yml`, element in the `members` list can optionally just be:

    ```
    - section: Current members
      members:
          - name: Hassan Jawahery
            title: Distinguished University Professor and the Gus T. Zorn Professor
            email: jawahery@umd.edu
            address: 3208G Physical Sciences Complex
          - name: Manuel Franco Sevilla
            title: Assistant Professor
            email: manuelf@umd.edu
            address: 3114 Physical Sciences Complex
            website: http://flavor.physics.umd.edu/manuelf
          - linebreak: true  # <--- here a smart line break will be inserted
    ```

    This line break has the advantage of **NOT** messing up in the mobile layout.

3. Added `Gemfile.lock` to pinpoint specific `jekyll` and all other Ruby gem versions. Don't remove it!

FYI @manuelfs
